import { type NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Animate from "../components/animate";
import InitialView from "../components/InitialView";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fanalyzer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative flex w-full flex-col items-center">
        <Header />
        <InitialView />
        <Animate>
          <div className="container flex min-h-screen w-full max-w-[1280px] flex-wrap items-center self-center py-5">
            <div className="w-1/2 flex-col">
              <h1 className="py-1 text-2xl font-bold md:text-4xl">
                Data Visualizations made{" "}
                <span className="text-[#FF8200]">easy.</span>
              </h1>
              <p className="pb-1 text-xl">
                Fanalyzer allows you to input your own sports data, create
                visualizations with our visualizations tool, and share them with
                other people.
              </p>
            </div>
            <div className="h-40 w-40 flex-col bg-gray-400 md:ml-auto md:h-80 md:w-80" />
          </div>
        </Animate>

        <Animate>
          <div className="container flex min-h-screen w-full max-w-[1280px] flex-wrap-reverse items-center justify-center self-center">
            <div className="h-40 w-40 flex-col bg-gray-400 md:mr-auto md:h-80 md:w-80" />
            <div className="w-1/2 flex-col md:ml-10 ">
              <h1 className="py-1  text-3xl font-bold">
                <span className="text-[#FF8200]">Interactive</span>{" "}
                visualizations for your sports data
              </h1>
              <p className="pb-1 text-xl">
                Use our visualization tools to manipulate your data and graphs
                to create insightful visualizations to share.
              </p>
            </div>
          </div>
        </Animate>

        <Animate>
          <div className="container flex min-h-screen w-full max-w-[1280px] items-center justify-center self-center text-center">
            <div className="flex flex-col">
              <h2 className="flex self-center py-10 text-center text-3xl font-bold">
                Visualization Types
              </h2>
              <div className="grid grid-cols-4 gap-10">
                <div className="flex flex-col items-center text-2xl">
                  <div className="h-10 w-10 flex-col bg-gray-400 md:h-20 md:w-20" />
                  <span>V1</span>
                </div>
                <div className="flex flex-col items-center text-2xl">
                  <div className="h-10 w-10 flex-col bg-gray-400 md:h-20 md:w-20" />
                  V2
                </div>
                <div className="flex flex-col items-center text-2xl">
                  <div className="h-10 w-10 flex-col bg-gray-400 md:h-20 md:w-20" />
                  V3
                </div>
                <div className="flex flex-col items-center text-2xl">
                  <div className="h-10 w-10 flex-col bg-gray-400 md:h-20 md:w-20" />
                  V4
                </div>
              </div>
            </div>
          </div>
        </Animate>

        <Animate>
          <div className="container flex min-h-screen w-full max-w-[1280px] items-center justify-center self-center text-center">
            <div className="flex flex-col">
              <h1 className="text-md py-10 text-3xl font-bold">
                Supported Data Formats<br></br>
              </h1>
              <div className="grid grid-cols-4 gap-10">
                <div className="flex flex-col items-center text-2xl">
                  <div className="h-10 w-10 flex-col bg-gray-400 md:h-20 md:w-20" />
                  CSV
                </div>
                <div className="flex flex-col items-center text-2xl">
                  <div className="h-10 w-10 flex-col bg-gray-400 md:h-20 md:w-20" />
                  XLSX
                </div>
                <div className="flex flex-col items-center text-2xl">
                  <div className="h-10 w-10 flex-col bg-gray-400 md:h-20 md:w-20" />
                  JSON
                </div>
                <div className="flex flex-col items-center text-2xl">
                  <div className="h-10 w-10 flex-col bg-gray-400 md:h-20 md:w-20" />
                  XML
                </div>
              </div>
            </div>
          </div>
        </Animate>
      </main>
    </>
  );
};

export default Home;
