import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import Header from '../component/header'

import { api } from "../utils/api";
import Animate from "../component/animate"

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Fanalyzer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="md:pl-20 min-h-screen text-white bg-gradient-to-br from-[#0B546B] via-[#7D244F] to-[#FF8200]">
          <Header/>
          <div className="container flex flex-wrap items-center justify-center py-16">
            <div className="flex-col md:mr-10">
              <h1 className="font-bold text-2xl md:text-8xl">Sports Visualizations<br/>for Everyone</h1>
              <p className="py-2 md:text-4xl md:py-10">More about Fanalyzer here...</p>
              <button className="py-2 px-6 shadow-sm rounded-md bg-[#FF8200] md:text-2xl md:py-4 md:px-12">Sign Up</button>
            </div>
            <div className="flex-col w-40 h-40 mt-10 ml-5 bg-gray-100 md:w-96 md:h-96 md:mt-0"/>
          </div>
        </div>

        <Animate>
        <div className="container flex flex-wrap items-center justify-center py-16 px-20">
            <div className="flex-col md:mr-10 md:w-1/2">
              <h1 className="font-bold py-1 text-2xl md:text-4xl">Data Visualizations made <span className="text-[#FF8200]">easy</span></h1>
              <p className="pb-1 md:text-2xl">Fanalyzer allows you to input your own sports data, create visualizations with our visualizations tool, and share them with other people.</p>
            </div>
            <div className="flex-col w-40 h-40 bg-gray-400 md:w-80 md:h-80"/>
        </div>
        </Animate>

        <Animate>
        <div className="container flex flex-wrap-reverse items-center justify-center py-16 px-20">
          <div className="flex-col w-40 h-40 bg-gray-400 md:w-80 md:h-80"/>
          <div className="flex-col md:ml-10 md:w-1/2 ">
            <h1 className="font-bold py-1 text-2xl md:text-4xl"><span className="text-[#FF8200]">Interactive</span> visualizations for your sports data</h1>
            <p className="pb-1 md:text-2xl">Use our visualization tools to manipulate your data and graphs to create insightful visualizations to share.</p>
          </div>
        </div>
        </Animate>

        <Animate>
        <div className="container flex items-center justify-center text-center">
          <div className="flex-col">
              <div className="flex font-bold py-10 text-md md:text-4xl">Visualization Types<br></br></div>
              <div className="flex flex-wrap">
                <div className="flex-col mr-1 md:mr-10 md:text-2xl">
                  <div className="flex-col w-10 h-10 bg-gray-400 md:w-20 md:h-20"/>
                  V1
                </div>
                <div className="flex-col mr-1 md:mr-10 md:text-2xl">
                  <div className="flex-col w-10 h-10 bg-gray-400 md:w-20 md:h-20"/>
                  V2
                </div>
                <div className="flex-col mr-1 md:mr-10 md:text-2xl">
                  <div className="flex-col w-10 h-10 bg-gray-400 md:w-20 md:h-20"/>
                  V3
                </div>
                <div className="flex-col mr-1 md:mr-10 md:text-2xl">
                  <div className="flex-col w-10 h-10 bg-gray-400 md:w-20 md:h-20"/>
                  V4
                </div>
              </div>
          </div>
        </div>
        </Animate>

        <Animate>
        <div className="container flex items-center justify-center text-center">
          <div className="flex-col">
              <h1 className="font-bold py-10 text-md md:text-4xl">Supported Data Formats<br></br></h1>
              <div className="flex flex-wrap">
                <div className="flex-col mr-1 mb-10 md:mr-10 md:text-2xl">
                  <div className="flex-col w-10 h-10 bg-gray-400 md:w-20 md:h-20"/>
                  CSV
                </div>
                <div className="flex-col mr-1 md:mr-10 md:text-2xl">
                  <div className="flex-col w-10 h-10 bg-gray-400 md:w-20 md:h-20"/>
                  XLSX
                </div>
                <div className="flex-col mr-1 md:mr-10 md:text-2xl">
                  <div className="flex-col w-10 h-10 bg-gray-400 md:w-20 md:h-20"/>
                  JSON
                </div>
                <div className="flex-col mr-1 md:mr-10 md:text-2xl">
                  <div className="flex-col w-10 h-10 bg-gray-400 md:w-20 md:h-20"/>
                  XML
                </div>
              </div>
          </div>
        </div>
        </Animate>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};