import { type NextPage } from "next";
import Head from "next/head";
import Image from 'next/image'
import nolan_img from '../../public/images/nolan.png'

const Nolan: NextPage = () => {
  
    return (
      <>
        <Head>
          <title>Fanalyzer | About</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="px-20 min-h-screen text-white bg-gradient-to-br from-[#0B546B] via-[#7D244F] to-[#FF8200]">
            <div className="container flex justify-center sm:py-16">
                <Image className="flex-col w-1/2 h-1/2 sm:w-60 sm:h-70" src={nolan_img} alt="Picture of Nolan" width="240" height="240"/>
                <div className="flex-col pl-5 w-1/2 sm:w-1/4">
                    <h1 className="text-lg font-bold sm:xl">Nolan Askew</h1>
                    <div className="text-xs sm:text-base">
                        Computer science major at the University of Tennessee, Knoxville<br/><br/>Hack4Impact UTK - Director of Project Sourcing<br/><br/>1794 Scholar<br/><br/>
                        <a href="mailto:naskew@vols.utk.edu">naskew@vols.utk.edu</a>
                    </div>
                </div>
            </div>
        </main>
      </>
    );
  };
  
  export default Nolan;